version: 2.17
jobs:
  build:
    steps:
      - checkout
      - run:
        name: Install
        command: npm install
      - run:
        name: Build
        command: npm run build
      - run:
        name: Coverage
        command: npm run coverage
      - run:
        name: ESLint
        command: npm run eslint